package com.idb.mcore.domain;
// Generated May 26, 2017 9:52:35 AM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Subscriptions generated by hbm2java
 */
@Entity
@Table(name = "subscriptions", catalog = "sts_subscriptions")
public class Subscription implements java.io.Serializable {

	/**
	 * Serial Version UID
	 */
	private static final long serialVersionUID = 1851568218888306612L;
	/**
	 * ID of the msisdn in the database
	 */
	private Long id;
	/**
	 * MSISDN that belongs to the billing GUID
	 */
	private String msisdn;
	/**
	 * Billing GUID. One msisdn cannot be subscribed two times on the same GUID.
	 * This will cause double billing.
	 */
	private String billingGuid;

	private Date timestamp;

	public Subscription() {
	}

	public Subscription(final String msisdn, final String billingGuid) {
		this.msisdn = msisdn;
		this.billingGuid = billingGuid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(final Long id) {
		this.id = id;
	}

	@Column(name = "msisdn")
	public String getMsisdn() {
		return this.msisdn;
	}

	public void setMsisdn(final String msisdn) {
		this.msisdn = msisdn;
	}

	@Column(name = "billing_guid", length = 60)
	public String getBillingGuid() {
		return this.billingGuid;
	}

	public void setBillingGuid(final String billingGuid) {
		this.billingGuid = billingGuid;
	}

	@Column(name = "timestamp", insertable = false, updatable = false)
	@Temporal(TemporalType.TIMESTAMP)
	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(final Date timestamp) {
		this.timestamp = timestamp;
	}

}
